adding ruff pre-commit
fredpell1/YADLL pull request #32
Opened 2023-08-06 14:27 UTC by Transurgeon

This PR adds pre-commits (ruff) to the repository as a CI.
Also updates the requirements.txt
Closes #30

2023-08-06 18:08 UTC, fredpell1 requested changes

2023-08-06 18:08 UTC, fredpell1 commented on .pre-commit-config.yaml
it currently only outputs warning without refactoring the code

2023-08-06 19:06 UTC, Transurgeon commented on .pre-commit-config.yaml
I added black now, it should be working (it only reformats files that have received changes though, which makes sense)

2023-08-06 19:40 UTC, fredpell1 commented on .pre-commit-config.yaml
nice it works, could we add this to the github workflows so that it runs on PRs instead as a gh action? This would remove the need for the local ruff and black dependency

2023-08-06 20:26 UTC, Transurgeon commented on .pre-commit-config.yaml
@fredpell1 
I think ruff is supposed to be used as a pre-commit so that it warns you before making a commit. 
I can check to remove black and add that as a gh action.

2023-08-06 20:27 UTC, Transurgeon commented on .pre-commit-config.yaml
I am not sure if the gh action is allowed to modify code though, wouldn't that break some security policy?

2023-08-07 13:25 UTC, Transurgeon commented
@fredpell1 made another commit, I updated the workflow to copy the one from your project.

2023-08-07 15:02 UTC, Transurgeon commented on yadll/tensor/test.py
ok will do

2023-08-07 15:07 UTC, fredpell1 approved these changes

2023-08-07 15:09 UTC, fredpell1 commented
@Transurgeon is this ready for merging?

2023-08-07 15:10 UTC, fredpell1 approved these changes

2023-08-07 18:58 UTC, Transurgeon commented
> @Transurgeon is this ready for merging?

Yeah should be ok, I believe the CI builds only work from main (that's why we can't see them in this PR). So if it doesn't work we can always edit later.

2023-08-07 20:29 UTC, merged

2023-08-07 21:08 UTC, fredpell1 commented
@Transurgeon this was reverted because the action was failing.